apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraMounts:
    - hostPath: spark
      containerPath: /src
  extraPortMappings:
  - containerPort: 30092
    hostPort: 30092
    listenAddress: "0.0.0.0"
    protocol: tcp
- role: worker
  extraMounts:
    - hostPath: spark
      containerPath: /src
- role: worker
  extraMounts:
    - hostPath: spark
      containerPath: /src
- role: worker
  extraMounts:
    - hostPath: spark
      containerPath: /src