apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-connect
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka-connect
  template:
    metadata:
      labels:
        app: kafka-connect
    spec:
      containers:
        - name: kafka-connect
          image: kafka-konnect:1.0.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: "4Gi"
              cpu: "2"
            limits:
              memory: "6Gi"
              cpu: "4"
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "kafka-svc:9092"
            - name: CONNECT_GROUP_ID
              value: "connect-cluster"
            - name: CONNECT_CONFIG_STORAGE_TOPIC
              value: "connect-configs"
            - name: CONNECT_OFFSET_STORAGE_TOPIC
              value: "connect-offsets"
            - name: CONNECT_STATUS_STORAGE_TOPIC
              value: "connect-statuses"
            - name: CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
              value: "2"
            - name: CONNECT_KEY_CONVERTER
              value: "org.apache.kafka.connect.storage.StringConverter"
            - name: CONNECT_VALUE_CONVERTER
              value: "org.apache.kafka.connect.json.JsonConverter"
            - name: CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL
              value: "http://registry-schema:8081"
            - name: CONNECT_PLUGIN_PATH
              value: "/usr/share/confluent-hub-components,/etc/kafka-connect/jars,/connect-plugins,/plugins"
            - name: CONNECT_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: CONNECT_REST_ADVERTISED_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-connect
  namespace: kafka
spec:
  type: NodePort
  selector:
    app: kafka-connect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30094