apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: python-spark
  namespace: kafka
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark:3.5.5
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///src/spark.py
  sparkVersion: 3.5.5
  # sparkConf:
  #   spark.jars.packages: "org.apache.spark:spark-streaming-kafka-0-10_2.12:3.5.5,org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5,org.apache.kafka:kafka-clients:3.1.0"
  #   spark.driver.extraJavaOptions: "-Divy.cache.dir=/tmp -Divy.home=/tmp"
  deps:
    repositories:
      - https://mvnrepository.com/artifact/org.apache.spark/spark-streaming-kafka-0-10
      - https://mvnrepository.com/artifact/org.apache.spark/spark-sql-kafka-0-10
      - https://mvnrepository.com/artifact/org.apache.kafka/kafka-clients
    # packages:
    #   - org.apache.spark:spark-streaming-kafka-0-10_2.12:3.5.5
    #   - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5
    #   - org.apache.kafka:kafka-clients:3.1.0
  volumes:
    - name: "src"
      hostPath:
        path: "/src"
        type: Directory
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "src"
        mountPath: "/src"
  executor:
    instances: 1
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: "src"
        mountPath: "/src"