apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: python-spark
  namespace: kafka
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: python-spark:1.0.0
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///app/spark.py
  sparkVersion: 3.5.5
  driver:
    cores: 1
    memory: 512m
    serviceAccount: spark-operator-spark
  executor:
    instances: 1
    cores: 1
    memory: 512m