#!/bin/bash

source .env
WAIT_TIME=$(($WAIT_TIME/2))
curl -X DELETE http://localhost:8083/connectors/debezium-connector
kubectl exec service/kafka-svc -- kafka-topics.sh --bootstrap-server kafka-svc:9092 --delete --topic debezium.public.loggings
echo "Pause for $WAIT_TIME seconds..."
sleep $WAIT_TIME
kubectl exec -it statefulset/postgres -- psql -U postgres -c "DROP PUBLICATION debezium;"
kubectl exec -it statefulset/postgres -- psql -U postgres -c "select pg_drop_replication_slot('debezium');"
curl -X POST -H 'Content-Type: application/json' --data @configs/post/debezium-connector.json http://localhost:8083/connectors | json_pp
echo "Pause for another $WAIT_TIME seconds..."
sleep $WAIT_TIME
kubectl exec -it statefulset/postgres -- psql -U postgres -c "CREATE PUBLICATION debezium FOR ALL TABLES WITH (publish = 'insert, update, delete');"
kubectl exec -it statefulset/postgres -- psql -U postgres -c "SELECT pg_create_logical_replication_slot('debezium', 'pgoutput');"
sleep $WAIT_TIME
curl -X PUT -H "Content-Type: application/json" --data @configs/put/debezium-connector.json http://localhost:8083/connectors/debezium-connector/config | json_pp