#!/bin/bash

source .env
docker pull spark:3.5.5
kind load docker-image spark:3.5.5
kubectl delete -f manifests/9-pyspark.yml 2> /dev/null
kubectl apply -f manifests/9-pyspark.yml
sleep $WAIT_TIME
kubectl describe sparkapplications.sparkoperator.k8s.io python-spark
kubectl logs -f python-spark-driver