#!/bin/bash

kubectl config view | grep namespace | sed 's/  //g'
printf "\nNodes:\n"
kubectl get nodes
printf "\nConfigMaps:\n"
kubectl get configmaps
printf "\nServices:\n"
kubectl get services
printf "\nStatefulSets:\n"
kubectl get statefulsets
printf "\nDeployments:\n"
kubectl get deployments
printf "\nPods:\n"
kubectl get pods
printf "\nConnector Status:\n"
curl http://localhost:8083/connectors/postgres-sink-connector/status | json_pp
curl http://localhost:8083/connectors/debezium-connector/status | json_pp
printf "\nReplication Slots:\n"
kubectl exec -it statefulset/postgres -- psql -U postgres -c "SELECT * FROM pg_replication_slots;"
kubectl exec -it statefulset/postgres -- psql -U postgres -c "SELECT * FROM pg_stat_replication_slots;"
printf "\nPublications:\n"
kubectl exec -it statefulset/postgres -- psql -U postgres -c "SELECT * FROM pg_publication;"
kubectl exec -it statefulset/postgres -- psql -U postgres -c "SELECT * FROM pg_publication_tables;"
printf "\nTopics:\n"
kubectl exec service/kafka-svc -- kafka-topics.sh --list --bootstrap-server localhost:9092
printf "\nMessages:\n"
kubectl exec service/kafka-svc -- kafka-run-class.sh kafka.tools.GetOffsetShell --bootstrap-server kafka-svc:9092 --exclude-internal-topics | grep 'loggings'
printf "\nPort Mappings:\n"
ps aux | grep port-forward